import { axiosIntance } from "@/lib/axios";
import {
  Container,
  Heading,
  Spinner,
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [students, setStudents] = useState([]); //Simpan data response dari API
  const [isLoading, setIsLoading] = useState(false);
  const fetchStudents = async () => {
    setIsLoading(true);
    try {
      // Tambahkan timeout untuk menunggu 2 detik sebelum memanggil API
      setTimeout(async () => {
        // buat library untuk membuat base url di setiap endpointnya
        const stundentsResponse = await axiosIntance.get(
          "/api/student"
        );
        // console.log(stundentsResponse);
        setStudents(stundentsResponse.data.data);
        setIsLoading(false);
      }, 2000);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    fetchStudents();
  }, []);

  const renderProducts = () => {
    return students.map((student) => {
      return (
        <Tr key={student._id}>
          <Td>{student._id}</Td>
          <Td>{student.nama}</Td>
          <Td>{student.tanggalLahir}</Td>
          <Td>{student.jenisKelamin}</Td>
          <Td>{student.alamat}</Td>
          <Td>{student.kelas}</Td>
          <Td>{student.jurusan}</Td>
        </Tr>
      );
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Home Page</Heading>
          <Table>
            <Thead>
              <Tr>
                <Th>ID</Th>
                <Th>Nama</Th>
                <Th>Tanggal Lahir</Th>
                <Th>Jenis Kelamin</Th>
                <Th>Alamat</Th>
                <Th>Kelas</Th>
                <Th>Jurusan</Th>
              </Tr>
            </Thead>
            <Tbody>
              {isLoading ? <Spinner /> : null}
              {renderProducts()}
            </Tbody>
          </Table>
        </Container>
      </main>
    </>
  );
}
